name: Build WF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu01
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Maven Build
        run: mvn clean install
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Maven Test
        run: mvn test
    
      - name: Checkstyle
        run: mvn checkstyle:checkstyle
